### ISSUE TITLE
EBB SB2209 with Manta M8P

### ISSUE THREAD

**Issue by rwmagee90** [bigtreetech/EBB#60]
I am getting the below error message when running the python3 flash_can.py -i can0 -q command.

ERROR:root:Can Flash Error

Traceback (most recent call last):

File "/home/biqu/CanBoot/scripts/flash_can.py", line 493, in run_query

self.cansock.bind((intf,))

OSError: [Errno 19] No such device

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

File "/home/biqu/CanBoot/scripts/flash_can.py", line 621, in main

loop.run_until_complete(sock.run_query(intf))

File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete

return future.result()

File "/home/biqu/CanBoot/scripts/flash_can.py", line 495, in run_query

raise FlashCanError("Unable to bind socket to can0")

FlashCanError: Unable to bind socket to can0

biqu@BTT-CB1:~/CanBoot/scripts$ File "/home/biqu/CanBoot/scripts/flash_can.py", line 495, in run_query

raise FlashCanError("Unable to bind socket to can0")

FlashCanError: Unable to bind socket to can0

python3 flash_can.py -i can0 -q

**Comment by rwmagee90** [comment]
Issue resolved. Bad Manta M8P board
